export const t = [
    {
      "teamId": 1610612737,
      "abbreviation": "ATL",
      "teamName": "Atlanta Hawks",
      "simpleName": "Hawks",
      "location": "Atlanta",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/ATL_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/ATL.svg",
      "conference": "East",
      "division": "Southeast",
      "shortName": "ATL"
    },
    {
      "teamId": 1610612738,
      "abbreviation": "BOS",
      "teamName": "Boston Celtics",
      "simpleName": "Celtics",
      "location": "Boston",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/BOS_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/BOS.svg",
      "conference": "East",
      "division": "Atlantic",
      "shortName": "BOS"
    },
    {
      "teamId": 1610612751,
      "abbreviation": "BKN",
      "teamName": "Brooklyn Nets",
      "simpleName": "Nets",
      "location": "Brooklyn",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/BKN_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/BKN.svg",
      "conference": "East",
      "division": "Atlantic",
      "shortName": "BKN"
    },
    {
      "teamId": 1610612766,
      "abbreviation": "CHA",
      "teamName": "Charlotte Hornets",
      "simpleName": "Hornets",
      "location": "Charlotte",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/CHA_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/CHA.svg",
      "conference": "East",
      "division": "Southeast",
      "shortName": "CHA"
    },
    {
      "teamId": 1610612741,
      "abbreviation": "CHI",
      "teamName": "Chicago Bulls",
      "simpleName": "Bulls",
      "location": "Chicago",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/CHI_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/CHI.svg",
      "conference": "East",
      "division": "Central",
      "shortName": "CHI"
    },
    {
      "teamId": 1610612739,
      "abbreviation": "CLE",
      "teamName": "Cleveland Cavaliers",
      "simpleName": "Cavaliers",
      "location": "Cleveland",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/CLE_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/CLE.svg",
      "conference": "East",
      "division": "Central",
      "shortName": "CLE"
    },
    {
      "teamId": 1610612742,
      "abbreviation": "DAL",
      "teamName": "Dallas Mavericks",
      "simpleName": "Mavericks",
      "location": "Dallas",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/DAL_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/DAL.svg",
      "conference": "West",
      "division": "Southwest",
      "shortName": "DAL"
    },
    {
      "teamId": 1610612743,
      "abbreviation": "DEN",
      "teamName": "Denver Nuggets",
      "simpleName": "Nuggets",
      "location": "Denver",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/DEN_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/DEN.svg",
      "conference": "West",
      "division": "Northwest",
      "shortName": "DEN", 
      "colorCode": "#0E2240"
    },
    {
      "teamId": 1610612765,
      "abbreviation": "DET",
      "teamName": "Detroit Pistons",
      "simpleName": "Pistons",
      "location": "Detroit",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/DET_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/DET.svg",
      "conference": "East",
      "division": "Central",
      "shortName": "DET"
    },
    {
      "teamId": 1610612744,
      "abbreviation": "GSW",
      "teamName": "Golden State Warriors",
      "simpleName": "Warriors",
      "location": "Golden State",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/GSW_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/GSW.svg",
      "conference": "West",
      "division": "Pacific",
      "shortName": "GS"
    },
    {
      "teamId": 1610612745,
      "abbreviation": "HOU",
      "teamName": "Houston Rockets",
      "simpleName": "Rockets",
      "location": "Houston",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/HOU_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/HOU.svg",
      "conference": "West",
      "division": "Southwest",
      "shortName": "HOU"
    },
    {
      "teamId": 1610612754,
      "abbreviation": "IND",
      "teamName": "Indiana Pacers",
      "simpleName": "Pacers",
      "location": "Indiana",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/IND_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/IND.svg",
      "conference": "East",
      "division": "Central",
      "shortName": "IND"
    },
    {
      "teamId": 1610612746,
      "abbreviation": "LAC",
      "teamName": "Los Angeles Clippers",
      "simpleName": "Clippers",
      "location": "Los Angeles",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/LAC_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/LAC.svg",
      "conference": "West",
      "division": "Pacific",
      "shortName": "LA"
    },
    {
      "teamId": 1610612747,
      "abbreviation": "LAL",
      "teamName": "Los Angeles Lakers",
      "simpleName": "Lakers",
      "location": "Los Angeles",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/LAL_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/LAL.svg",
      "conference": "West",
      "division": "Pacific",
      "shortName": "LA"
    },
    {
      "teamId": 1610612763,
      "abbreviation": "MEM",
      "teamName": "Memphis Grizzlies",
      "simpleName": "Grizzlies",
      "location": "Memphis",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/MEM_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/MEM.svg",
      "conference": "West",
      "division": "Southwest",
      "shortName": "MEM"
    },
    {
      "teamId": 1610612748,
      "abbreviation": "MIA",
      "teamName": "Miami Heat",
      "simpleName": "Heat",
      "location": "Miami",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/MIA_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/MIA.svg",
      "conference": "East",
      "division": "Southeast",
      "shortName": "MIA"
    },
    {
      "teamId": 1610612749,
      "abbreviation": "MIL",
      "teamName": "Milwaukee Bucks",
      "simpleName": "Bucks",
      "location": "Milwaukee",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/MIL_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/MIL.svg",
      "conference": "East",
      "division": "Central",
      "shortName": "MIL"
    },
    {
      "teamId": 1610612750,
      "abbreviation": "MIN",
      "teamName": "Minnesota Timberwolves",
      "simpleName": "Timberwolves",
      "location": "Minnesota",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/MIN_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/MIN.svg",
      "conference": "West",
      "division": "Northwest",
      "shortName": "MIN"
    },
    {
      "teamId": 1610612740,
      "abbreviation": "NOP",
      "teamName": "New Orleans Pelicans",
      "simpleName": "Pelicans",
      "location": "New Orleans",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/NOP_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/NOP.svg",
      "conference": "West",
      "division": "Southwest",
      "shortName": "NO"
    },
    {
      "teamId": 1610612752,
      "abbreviation": "NYK",
      "teamName": "New York Knicks",
      "simpleName": "Knicks",
      "location": "New York",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/NYK_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/NYK.svg",
      "conference": "East",
      "division": "Atlantic",
      "shortName": "NY"
    },
    {
      "teamId": 1610612760,
      "abbreviation": "OKC",
      "teamName": "Oklahoma City Thunder",
      "simpleName": "Thunder",
      "location": "Oklahoma City",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/OKC_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/OKC.svg",
      "conference": "West",
      "division": "Northwest",
      "shortName": "OKC"
    },
    {
      "teamId": 1610612753,
      "abbreviation": "ORL",
      "teamName": "Orlando Magic",
      "simpleName": "Magic",
      "location": "Orlando",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/ORL_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/ORL.svg",
      "conference": "East",
      "division": "Southeast",
      "shortName": "ORL"
    },
    {
      "teamId": 1610612755,
      "abbreviation": "PHI",
      "teamName": "Philadelphia 76ers",
      "simpleName": "76ers",
      "location": "Philadelphia",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/PHI_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/PHI.svg",
      "conference": "East",
      "division": "Atlantic",
      "shortName": "PHI"
    },
    {
      "teamId": 1610612756,
      "abbreviation": "PHX",
      "teamName": "Phoenix Suns",
      "simpleName": "Suns",
      "location": "Phoenix",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/PHX_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/PHX.svg",
      "conference": "West",
      "division": "Pacific",
      "shortName": "PHX"
    },
    {
      "teamId": 1610612757,
      "abbreviation": "POR",
      "teamName": "Portland Trail Blazers",
      "simpleName": "Trail Blazers",
      "location": "Portland",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/POR_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/POR.svg",
      "conference": "West",
      "division": "Northwest",
      "shortName": "POR"
    },
    {
      "teamId": 1610612758,
      "abbreviation": "SAC",
      "teamName": "Sacramento Kings",
      "simpleName": "Kings",
      "location": "Sacramento",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/SAC_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/SAC.svg",
      "conference": "West",
      "division": "Pacific",
      "shortName": "SAC"
    },
    {
      "teamId": 1610612759,
      "abbreviation": "SAS",
      "teamName": "San Antonio Spurs",
      "simpleName": "Spurs",
      "location": "San Antonio",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/SAS_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/SAS.svg",
      "conference": "West",
      "division": "Southwest",
      "shortName": "SA"
    },
    {
      "teamId": 1610612761,
      "abbreviation": "TOR",
      "teamName": "Toronto Raptors",
      "simpleName": "Raptors",
      "location": "Toronto",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/TOR_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/TOR.svg",
      "conference": "East",
      "division": "Atlantic",
      "shortName": "TOR",
      "colorCode": "#CE1141"
    },
    {
      "teamId": 1610612762,
      "abbreviation": "UTA",
      "teamName": "Utah Jazz",
      "simpleName": "Jazz",
      "location": "Utah",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/UTA_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/UTA.svg",
      "conference": "West",
      "division": "Northwest",
      "shortName": "UTA"
    },
    {
      "teamId": 1610612764,
      "abbreviation": "WAS",
      "teamName": "Washington Wizards",
      "simpleName": "Wizards",
      "location": "Washington",
      "logoUrl": "https://stats.nba.com/media/img/teams/logos/WAS_logo.svg",
      "altLogo": "https://cdn.nba.net/assets/logos/teams/secondary/web/WAS.svg",
      "conference": "East",
      "division": "Southeast",
      "shortName": "WAS"
    },
  ];

